"""Writer agent specialized in content creation and documentation."""

from __future__ import annotations

import time
from typing import Any, Dict

import structlog

from src.agents.base_agent import AgentCapability, BaseAgent
from src.tasks.task import Task, TaskResult

logger = structlog.get_logger(__name__)


class WriterAgent(BaseAgent):
    """Agent specialized in writing, documentation, and content creation.

    Capabilities include technical writing, documentation generation,
    content creation, copywriting, and format conversion.
    """

    def __init__(self, name: str = "Writer", config: Dict[str, Any] | None = None) -> None:
        capabilities = [
            AgentCapability("content_creation", 0.95, "Create original content"),
            AgentCapability("documentation", 0.90, "Write clear documentation"),
            AgentCapability("communication", 0.85, "Communicate ideas effectively"),
            AgentCapability("technical_writing", 0.85, "Write technical documents"),
            AgentCapability("editing", 0.80, "Edit and refine written content"),
        ]
        super().__init__(
            name=name,
            agent_type="writer",
            capabilities=capabilities,
            max_concurrent_tasks=2,
            config=config,
        )
        self._style_guide = (config or {}).get("style_guide", "technical")
        self._log = logger.bind(agent_id=self.id, agent_type="writer")

    def _perform_task(self, task: Task) -> TaskResult:
        """Execute writing-oriented tasks.

        Args:
            task: A task requiring writing capabilities.

        Returns:
            Written content or documentation.
        """
        start = time.monotonic()
        self._log.info("writing_started", task_id=task.id)

        content_type = task.context.get("content_type", "documentation")
        audience = task.context.get("audience", "technical")
        tone = task.context.get("tone", "professional")
        length = task.context.get("length", "medium")
        topics = task.context.get("topics", [task.description])

        content = self._create_content(
            content_type, audience, tone, length, topics
        )

        word_count = len(content.split())
        duration = time.monotonic() - start
        self._log.info(
            "writing_completed",
            task_id=task.id,
            word_count=word_count,
            content_type=content_type,
        )

        return TaskResult(
            task_id=task.id,
            agent_id=self.id,
            success=True,
            output=content,
            metadata={
                "content_type": content_type,
                "audience": audience,
                "tone": tone,
                "word_count": word_count,
                "style_guide": self._style_guide,
            },
            duration_seconds=duration,
        )

    def _create_content(
        self,
        content_type: str,
        audience: str,
        tone: str,
        length: str,
        topics: list[str],
    ) -> str:
        """Simulate content creation.

        Args:
            content_type: Type of content to produce.
            audience: Target audience.
            tone: Writing tone.
            length: Desired length.
            topics: Topics to cover.

        Returns:
            Generated content.
        """
        length_multipliers = {"brief": 1, "short": 2, "medium": 4, "long": 6, "comprehensive": 8}
        mult = length_multipliers.get(length, 4)

        topic_sections = "\n\n".join(
            f"## {i+1}. {topic}\n\n"
            f"This section covers {topic} in detail, providing "
            f"comprehensive information tailored for {audience} audiences. "
            f"The content is written in a {tone} tone to ensure "
            f"clarity and engagement."
            for i, topic in enumerate(topics)
        )

        paragraphs = "\n\n".join(
            f"This paragraph expands on the key points with additional "
            f"context and examples relevant to {audience}."
            for _ in range(mult)
        )

        return (
            f"# {content_type.replace('_', ' ').title()}\n\n"
            f"**Audience**: {audience} | **Tone**: {tone} | **Length**: {length}\n\n"
            f"---\n\n"
            f"{topic_sections}\n\n"
            f"{paragraphs}\n\n"
            f"---\n\n"
            f"*Generated by WriterAgent | Style: {self._style_guide}*\n"
        )
